#!/system/bin/sh

DATA_APP=/data/app
FLYME_APP=/data/media/app
FLYME_FONT=/data/media/fonts
SYSTEM_APP_DIR=/system/app
SYSTEM_PRIV_APP_DIR=/system/priv-app

mount -o remount /system

for file in `grep -rns "app2data" /system/etc/data.conf | cut -d "=" -f2`
do
	if [ ! -d "$DATA_APP/$file" ];then
		cp -rf $FLYME_APP/$file $DATA_APP/
	fi
	if [ ! -L "$SYSTEM_APP_DIR/$file" ];then
		ln -s $FLYME_APP/$file $SYSTEM_APP_DIR/$file
	fi
done

for file in `grep -rns "priv_app2data" /system/etc/data.conf | cut -d "=" -f2`
do
	if [ ! -d "$DATA_APP/$file" ];then
		cp -rf $FLYME_APP/$file $DATA_APP/
	fi
	if [ ! -L "$SYSTEM_PRIV_APP_DIR/$file" ];then
		ln -s $FLYME_APP/$file $SYSTEM_PRIV_APP_DIR/$file
	fi
done

for file in `grep -rns "fonts2data" /system/etc/data.conf | cut -d "=" -f2`
do
	if [ ! -L "/system/fonts/$file" ];then
		ln -s $FLYME_FONT/$file /system/fonts/$file
	fi
done
